let data=[];
const map=L.map('map',{zoomControl:true,worldCopyJump:true}).setView([45,8],4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'',maxZoom:19}).addTo(map);map.attributionControl.setPrefix(false);
let filter='all',markers=[];let advancedFilter={country:'all',city:'',type:'all',precision:'all',accredited:false};const clusterLayer=L.markerClusterGroup({showCoverageOnHover:false,spiderfyOnMaxZoom:true,disableClusteringAtZoom:15,maxClusterRadius:(z)=>z>=13?28:z>=10?38:52,iconCreateFunction:clusterIcon});map.addLayer(clusterLayer);const panel=document.getElementById('panel'),detail=document.getElementById('detail');
function clusterIcon(cluster){const children=cluster.getAllChildMarkers();const counts={};children.forEach(m=>{const t=m.options.atlasType||'school';counts[t]=(counts[t]||0)+1});const dominant=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'school';const colors={school:'#0878d1',university:'#7836ce',language:'#f38b20',association:'#16a66c',teacher:'#eb218e',cervantes:'#d92525'};const n=cluster.getChildCount();const size=n<10?38:n<100?44:50;return L.divIcon({html:'<div class="atlas-cluster" style="--cluster:'+colors[dominant]+';width:'+size+'px;height:'+size+'px"><span>'+n+'</span></div>',className:'atlas-cluster-wrap',iconSize:[size,size]})}
function icon(type){const c={school:'#0c72b8',university:'#7557c9',language:'#e69032',association:'#31a47c'}[type]||'#0c72b8';return L.divIcon({className:'',html:"<div class='atlas-marker' style='width:20px;height:20px;background:"+c+"'></div>",iconSize:[20,20]})}
function liveStats(){const countries=new Set(data.map(x=>x.country).filter(Boolean)),cities=new Set(data.map(x=>(x.city||'')+'|'+(x.country||'')).filter(x=>!x.startsWith('|'))),cerv=data.filter(x=>x.type==='cervantes').length,acc=data.filter(x=>x.accreditation).length;return {institutions:data.length,countries:countries.size,cities:cities.size,cervantes:cerv,accredited:acc}}function updateLiveStats(){const st=liveStats();document.querySelectorAll('[data-live-stat]').forEach(el=>{const k=el.dataset.liveStat,n=el.querySelector('strong');if(n)n.textContent=(st[k]??0).toLocaleString()});const c=document.getElementById('count'),cc=document.getElementById('countries');if(c)c.textContent=st.institutions.toLocaleString();if(cc)cc.textContent=st.countries.toLocaleString()}function activateStat(kind){if(kind==='cervantes'){filter='cervantes';document.querySelectorAll('.chips button').forEach(x=>x.classList.toggle('active',x.dataset.filter==='cervantes'));render();document.getElementById('worldCard').classList.add('hidden')}else if(kind==='accredited'){advancedFilter={country:'all',city:'',type:'all',precision:'all',accredited:true};render();document.getElementById('worldCard').classList.add('hidden')}else if(kind==='institutions'){filter='all';advancedFilter={country:'all',city:'',type:'all',precision:'all',accredited:false};render();document.getElementById('worldCard').classList.add('hidden')}else if(kind==='countries'||kind==='cities'){document.getElementById('worldCard').classList.add('hidden');map.flyTo([20,5],2,{duration:1})}}document.addEventListener('click',e=>{const b=e.target.closest('[data-live-stat]');if(b)activateStat(b.dataset.liveStat)});
function render(){clusterLayer.clearLayers();markers=[];const shown=data.filter(x=>(filter==='all'||x.type===filter)&&(advancedFilter.country==='all'||x.country===advancedFilter.country)&&(!advancedFilter.city||normSearch(x.city).includes(normSearch(advancedFilter.city)))&&(advancedFilter.type==='all'||x.type===advancedFilter.type)&&(advancedFilter.precision==='all'||(x.precision||'unknown')===advancedFilter.precision)&&(!advancedFilter.accredited||!!x.accreditation));shown.forEach(x=>{let m=L.marker([x.lat,x.lng],{icon:icon(x.type),atlasType:x.type}).on('click',()=>show(x));markers.push(m)});clusterLayer.addLayers(markers);const c=document.getElementById('count');const cc=document.getElementById('countries');if(c)c.textContent=data.length.toLocaleString();if(cc)cc.textContent=new Set(data.map(x=>x.country)).size;if(globeInstance)globeInstance.pointsData(getGlobePoints(shown));updateLiveStats()}
function publicTypeLabel(type){const es=currentLang==='es';return {school:es?'Centro escolar':'School',university:es?'Universidad':'University',language:es?'Academia':'Language school',association:es?'Asociación':'Association',cervantes:'Cervantes',teacher:es?'Profesor':'Teacher',official:es?'Institución oficial':'Official institution'}[type]||type}
function precisionLabel(p){const es=currentLang==='es';return {exact:es?'Ubicación exacta':'Exact location',address:es?'Dirección verificada':'Verified address',city:es?'Ubicación por ciudad':'City-level location',region:es?'Ubicación regional':'Region-level location',unknown:es?'Ubicación por verificar':'Location to verify'}[p||'unknown']}
function show(x){const es=currentLang==='es',type=publicTypeLabel(x.type),addr=x.address?'<div class="profileAddress">⌖ '+x.address+'</div>':'',accr=x.accreditation?'<span class="profileBadge accredited">✓ '+(es?'Acreditado por Instituto Cervantes':'Instituto Cervantes Accredited')+'</span>':'',cerv=x.type==='cervantes'?'<span class="profileBadge cervantesBadge">● '+(es?'Red Instituto Cervantes':'Instituto Cervantes Network')+'</span>':'',verified=x.verified?'<span class="profileBadge verifiedBadge">✓ '+(es?'Verificado':'Verified')+'</span>':'',fedele=x.fedele?'<span class="profileBadge fedeleBadge">◆ FEDELE</span>':'',prec='<span class="profileBadge precisionBadge">⌖ '+precisionLabel(x.precision)+'</span>',web=x.web?String(x.web).trim():'',email=x.email?String(x.email).trim():'',phone=x.phone?String(x.phone).trim():'',contact=(web||email||phone)?'<div class="profileContact"><small>'+(es?'CONTACTO':'CONTACT')+'</small><div class="profileContactActions">'+(web?'<a class="contactWeb" target="_blank" rel="noopener" href="'+web+'">🌐 '+(es?'Página web':'Website')+' ↗</a>':'')+(email?'<a href="mailto:'+email+'">✉ '+email+'</a>':'')+(phone?'<a href="tel:'+phone.replace(/[^+0-9]/g,'')+'">☎ '+phone+'</a>':'')+'</div></div>':'';detail.innerHTML='<div class="institutionProfile type-'+x.type+'"><div class="profileType"><i></i>'+type+'</div><h2>'+x.name+'</h2><div class="profilePlace">📍 '+x.city+', '+x.country+'</div>'+addr+'<div class="profileBadges">'+cerv+accr+fedele+verified+prec+'</div>'+(x.program?'<div class="profileProgram"><small>'+(es?'ESPAÑOL / PROGRAMA':'SPANISH / PROGRAM')+'</small><strong>'+x.program+'</strong></div>':'')+contact+'<button class="profileSave" data-save-id="'+x.id+'">'+(isSaved(x.id)?'♥ '+(es?'Guardado en Mi Atlas':'Saved to My Atlas'):'♡ '+(es?'Guardar en Mi Atlas':'Save to My Atlas'))+'</button></div>';panel.style.display='block';const sb=detail.querySelector('[data-save-id]');if(sb)sb.onclick=()=>{toggleSaved(x.id);show(x)}}
document.querySelectorAll('.chips button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chips button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;render()});
const af=document.getElementById('advancedFilters');function populateAdvancedCountries(){const e=document.getElementById('afCountry'),v=e.value;e.innerHTML='<option value="all">All countries</option>'+[...new Set(data.map(x=>x.country))].sort().map(x=>'<option>'+x+'</option>').join('');if([...e.options].some(o=>o.value===v))e.value=v}document.getElementById('advancedFilterBtn').onclick=()=>{populateAdvancedCountries();af.classList.toggle('open')};document.getElementById('afClose').onclick=()=>af.classList.remove('open');document.getElementById('afApply').onclick=()=>{advancedFilter={country:document.getElementById('afCountry').value,city:document.getElementById('afCity').value.trim(),type:document.getElementById('afType').value,precision:document.getElementById('afPrecision').value,accredited:document.getElementById('afAccredited').checked};render();const n=data.filter(x=>(filter==='all'||x.type===filter)&&(advancedFilter.country==='all'||x.country===advancedFilter.country)&&(!advancedFilter.city||normSearch(x.city).includes(normSearch(advancedFilter.city)))&&(advancedFilter.type==='all'||x.type===advancedFilter.type)&&(advancedFilter.precision==='all'||(x.precision||'unknown')===advancedFilter.precision)&&(!advancedFilter.accredited||!!x.accreditation)).length;document.getElementById('afResult').textContent=n.toLocaleString()+' '+(currentLang==='es'?'resultados':'results')};document.getElementById('afClear').onclick=()=>{advancedFilter={country:'all',city:'',type:'all',precision:'all',accredited:false};document.getElementById('afCountry').value='all';document.getElementById('afCity').value='';document.getElementById('afType').value='all';document.getElementById('afPrecision').value='all';document.getElementById('afAccredited').checked=false;document.getElementById('afResult').textContent='';render()};document.getElementById('close').onclick=()=>panel.style.display='none';document.getElementById('explore').onclick=()=>{document.getElementById('worldCard').classList.add('hidden');map.flyTo([46,8],5,{duration:1.2})};map.on('zoomstart',()=>document.getElementById('worldCard').classList.add('hidden'));
const countryAliases={'espana':'Spain','spain':'Spain','eslovaquia':'Slovakia','slovakia':'Slovakia','alemania':'Germany','germany':'Germany','austria':'Austria','francia':'France','france':'France','italia':'Italy','italy':'Italy','reino unido':'United Kingdom','united kingdom':'United Kingdom','inglaterra':'United Kingdom','estados unidos':'United States','eeuu':'United States','usa':'United States','united states':'United States','canada':'Canada','rusia':'Russia','russia':'Russia','china':'China','india':'India','brasil':'Brazil','brazil':'Brazil','mexico':'Mexico','australia':'Australia','polonia':'Poland','poland':'Poland','hungria':'Hungary','hungary':'Hungary','chequia':'Czechia','republica checa':'Czechia','czechia':'Czechia','rumania':'Romania','romania':'Romania','bulgaria':'Bulgaria','portugal':'Portugal','irlanda':'Ireland','ireland':'Ireland','suiza':'Switzerland','switzerland':'Switzerland','suecia':'Sweden','sweden':'Sweden','noruega':'Norway','norway':'Norway','finlandia':'Finland','finland':'Finland','dinamarca':'Denmark','denmark':'Denmark','islandia':'Iceland','iceland':'Iceland','belgica':'Belgium','belgium':'Belgium','paises bajos':'Netherlands','netherlands':'Netherlands','grecia':'Greece','greece':'Greece','turquia':'Türkiye','turkey':'Türkiye','japon':'Japan','japan':'Japan','corea del sur':'South Korea','south korea':'South Korea','marruecos':'Morocco','morocco':'Morocco','argelia':'Algeria','algeria':'Algeria','egipto':'Egypt','egypt':'Egypt','sudafrica':'South Africa','south africa':'South Africa','nueva zelanda':'New Zealand','new zealand':'New Zealand','cuba':'Cuba'};
function normSearch(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
function fitRecords(rows,maxZoom=7){if(!rows.length)return false;const bounds=L.latLngBounds(rows.map(x=>[x.lat,x.lng]));if(rows.length===1)map.flyTo([rows[0].lat,rows[0].lng],Math.min(maxZoom,10));else map.flyToBounds(bounds.pad(.18),{maxZoom,duration:1.1});return true}
function showPlaceDirectory(title,rows,kind){const es=currentLang==='es',counts={};rows.forEach(x=>counts[x.type]=(counts[x.type]||0)+1);const order=['school','university','language','association','cervantes','teacher','official'];const chips=order.filter(t=>counts[t]).map(t=>'<span class="dirStat type-'+t+'"><i></i><b>'+counts[t]+'</b> '+publicTypeLabel(t)+'</span>').join('');const cities=kind==='country'?[...new Set(rows.map(x=>x.city).filter(Boolean))].length:null;const list=[...rows].sort((x,y)=>(x.city||'').localeCompare(y.city||'')||(x.name||'').localeCompare(y.name||'')).slice(0,250);detail.innerHTML='<div class="placeDirectory"><div class="dirEyebrow">ATLAS ELE · '+(kind==='country'?(es?'PAÍS':'COUNTRY'):(es?'CIUDAD':'CITY'))+'</div><h2>'+title+'</h2><div class="dirHeadline"><strong>'+rows.length.toLocaleString()+'</strong><span>'+(es?'instituciones':'institutions')+(cities!==null?' · '+cities+' '+(es?'ciudades':'cities'):'')+'</span></div><div class="dirStats">'+chips+'</div><div class="dirList">'+list.map(x=>'<button data-dir-id="'+x.id+'"><i class="dirDot type-'+x.type+'"></i><span><strong>'+x.name+'</strong><small>'+x.city+(kind==='city'?' · '+x.country:'')+'</small></span><em>›</em></button>').join('')+'</div>'+(rows.length>250?'<div class="dirMore">'+(es?'Mostrando los primeros 250 resultados':'Showing first 250 results')+'</div>':'')+'</div>';panel.style.display='block';detail.querySelectorAll('[data-dir-id]').forEach(btn=>btn.onclick=()=>{const x=data.find(r=>r.id===btn.dataset.dirId);if(x){map.flyTo([x.lat,x.lng],15,{duration:.8});show(x)}})}
function search(){const raw=document.getElementById('q').value.trim();if(!raw)return;const q=normSearch(raw),canonical=countryAliases[q]||null;const countries=canonical?data.filter(x=>x.country===canonical):data.filter(x=>normSearch(x.country)===q);if(countries.length){fitRecords(countries,6);showPlaceDirectory(canonical||countries[0].country,countries,'country');return}const cities=data.filter(x=>normSearch(x.city)===q);if(cities.length){fitRecords(cities,12);showPlaceDirectory(cities[0].city,cities,'city');return}const hit=data.find(x=>normSearch(x.name)===q)||data.find(x=>normSearch(x.name).includes(q));if(hit){map.flyTo([hit.lat,hit.lng],15,{duration:1.1});show(hit)}}
const searchSuggest=document.getElementById('searchSuggest');function suggestionIcon(type){return {school:'▣',university:'◆',language:'●',association:'●',cervantes:'●',teacher:'♥'}[type]||'•'}function buildSearchSuggestions(){const raw=document.getElementById('q').value.trim(),q=normSearch(raw);if(q.length<2){searchSuggest.classList.remove('open');searchSuggest.innerHTML='';return}const items=[],seen=new Set();const aliases=Object.entries(countryAliases).filter(([a])=>normSearch(a).includes(q)).slice(0,3);for(const [,country] of aliases){if(seen.has('c'+country))continue;seen.add('c'+country);const rows=data.filter(x=>x.country===country);if(rows.length)items.push({kind:'country',label:country,sub:rows.length+' '+(currentLang==='es'?'instituciones':'institutions'),rows})}const countryNames=[...new Set(data.map(x=>x.country))].filter(x=>normSearch(x).includes(q)).slice(0,3);for(const country of countryNames){if(seen.has('c'+country))continue;seen.add('c'+country);const rows=data.filter(x=>x.country===country);items.push({kind:'country',label:country,sub:rows.length+' '+(currentLang==='es'?'instituciones':'institutions'),rows})}const cityNames=[...new Set(data.map(x=>x.city).filter(Boolean))].filter(x=>normSearch(x).includes(q)).slice(0,5);for(const city of cityNames){const rows=data.filter(x=>x.city===city);items.push({kind:'city',label:city,sub:rows[0]?.country+' · '+rows.length+' '+(currentLang==='es'?'instituciones':'institutions'),rows})}data.filter(x=>normSearch(x.name).includes(q)).slice(0,7).forEach(x=>items.push({kind:'record',label:x.name,sub:x.city+', '+x.country,row:x,type:x.type}));const final=items.slice(0,10);searchSuggest.innerHTML=final.map((x,i)=>'<button data-si="'+i+'"><b class="'+(x.type?'type-'+x.type:'')+'">'+(x.kind==='country'?'🌍':x.kind==='city'?'📍':suggestionIcon(x.type))+'</b><span><strong>'+x.label+'</strong><small>'+x.sub+'</small></span><em>'+(x.kind==='country'?(currentLang==='es'?'País':'Country'):x.kind==='city'?(currentLang==='es'?'Ciudad':'City'):publicTypeLabel(x.type))+'</em></button>').join('');searchSuggest.classList.toggle('open',!!final.length);searchSuggest.querySelectorAll('[data-si]').forEach(btn=>btn.onclick=()=>{const x=final[+btn.dataset.si];searchSuggest.classList.remove('open');document.getElementById('q').value=x.label;if(x.kind==='country'){fitRecords(x.rows,6);showPlaceDirectory(x.label,x.rows,'country')}else if(x.kind==='city'){fitRecords(x.rows,12);showPlaceDirectory(x.label,x.rows,'city')}else{map.flyTo([x.row.lat,x.row.lng],15,{duration:.8});show(x.row)}})}document.getElementById('q').addEventListener('input',buildSearchSuggestions);document.getElementById('q').addEventListener('focus',buildSearchSuggestions);document.addEventListener('click',e=>{if(!e.target.closest('.search'))searchSuggest.classList.remove('open')});
document.getElementById('searchBtn').onclick=search;document.getElementById('q').addEventListener('keydown',e=>{if(e.key==='Enter')search()});
const teacherCard=document.getElementById('teacherCard');
document.getElementById('joinBtn').onclick=()=>{teacherCard.classList.add('open');document.getElementById('worldCard').classList.add('hidden')};
document.getElementById('teacherClose').onclick=()=>teacherCard.classList.remove('open');
document.getElementById('teachersChip').onclick=(e)=>{e.stopPropagation();teacherCard.classList.add('open');document.querySelectorAll('.chips button').forEach(x=>x.classList.remove('active'));document.getElementById('teachersChip').classList.add('active')};

const translations={
en:{tagline:'THE GLOBAL MAP OF SPANISH TEACHING',searchPlaceholder:'Search for a country, city, institution or teacher…',search:'Search',admin:'Admin',contact:'Contact',contactTitle:'Contact',contactText:'Questions, corrections or collaboration ideas? Get in touch with ATLAS ELE.',contactName:'Name',contactEmail:'Email',contactSubject:'Subject',contactMessage:'Message',contactSend:'Send message →',contactOr:'Prefer email?',all:'▦ All',school:'▣ Schools',university:'◆ Universities',language:'● Language Schools',association:'● Associations',cervantes:'● Cervantes',teachers:'● Teachers',more:'More',add:'Add place',teacherCta:'Put yourself on the map',eyebrow:'SPANISH TEACHING WORLDWIDE',headline:'Explore a world<br>connected by Spanish.',desc:'Discover schools, universities, language centres and professional communities teaching Spanish around the globe.',institutions:'institutions',countries:'countries',growth:'A growing community',atlasTeachers:'ATLAS teachers',exploreMap:'Explore the map ↓',teacherHeart:'TEACHERS ARE THE HEART OF ATLAS ELE',put:'Put yourself<br>on the map.',teacherDesc:'Are you a Spanish teacher? Join the global community and choose how you want to appear: by institution, city, country — or stay private.',privacy:'🔒 Your email will never appear publicly.',registration:'Teacher registration coming next →',mapped:'mapped',community:'Community-powered',legend:['School','University','Language school','Association','Cervantes','Teacher'],moreItems:['Explore by country','Top ELE cities','Official institutions','Publishers','Teacher training','Communities','Events & conferences','ELE projects'],visit:'Visit institution ↗',publicProfile:'Public ATLAS ELE profile. Private/internal contact information is not exposed.',verified:'✓ Verified',demo:'≈ Demo location'},
es:{tagline:'EL MAPA MUNDIAL DE LA ENSEÑANZA DEL ESPAÑOL',searchPlaceholder:'Busca un país, ciudad, institución o profesor…',search:'Buscar',admin:'Admin',contact:'Contacto',contactTitle:'Contacto',contactText:'¿Preguntas, correcciones o ideas para colaborar? Escríbenos a ATLAS ELE.',contactName:'Nombre',contactEmail:'Correo electrónico',contactSubject:'Asunto',contactMessage:'Mensaje',contactSend:'Enviar mensaje →',contactOr:'¿Prefieres el correo?',all:'▦ Todo',school:'▣ Centros escolares',university:'◆ Universidades',language:'● Academias',association:'● Asociaciones',cervantes:'● Cervantes',teachers:'● Profesores',more:'Más',add:'Añadir centro',teacherCta:'Ponte en el mapa',eyebrow:'LA ENSEÑANZA DEL ESPAÑOL EN EL MUNDO',headline:'Explora un mundo<br>conectado por el español.',desc:'Descubre colegios, universidades, academias y comunidades profesionales que enseñan español en todo el mundo.',institutions:'instituciones',countries:'países',growth:'Una comunidad en crecimiento',atlasTeachers:'profesores ATLAS',exploreMap:'Explorar el mapa ↓',teacherHeart:'LOS PROFESORES SON EL CORAZÓN DE ATLAS ELE',put:'Ponte<br>en el mapa.',teacherDesc:'¿Eres profesor de español? Únete a la comunidad global y decide cómo quieres aparecer: por institución, ciudad, país o de forma privada.',privacy:'🔒 Tu correo electrónico nunca aparecerá públicamente.',registration:'Registro de profesores próximamente →',mapped:'en el mapa',community:'Impulsado por la comunidad',legend:['Centro escolar','Universidad','Academia','Asociación','Cervantes','Profesor'],moreItems:['Explorar por país','Principales ciudades ELE','Instituciones oficiales','Editoriales','Formación de profesores','Comunidades','Eventos y congresos','Proyectos ELE'],visit:'Visitar institución ↗',publicProfile:'Perfil público de ATLAS ELE. La información de contacto privada o interna no se muestra.',verified:'✓ Verificado',demo:'≈ Ubicación aproximada'}
};
let currentLang=localStorage.getItem('atlasLang')||((navigator.language||'').toLowerCase().startsWith('es')?'es':'en');
function applyLanguage(lang){
 currentLang=lang;localStorage.setItem('atlasLang',lang);document.documentElement.lang=lang;const t=translations[lang];
 document.getElementById('tagline').textContent=t.tagline;document.getElementById('q').placeholder=t.searchPlaceholder;document.getElementById('searchBtn').textContent=t.search;
 document.getElementById('adminLabel').textContent=t.admin;document.getElementById('contactLabel').textContent=t.contact;
 const ct={contactTitle:'contactTitle',contactText:'contactText',contactName:'contactNameLabel',contactEmail:'contactEmailLabel',contactSubject:'contactSubjectLabel',contactMessage:'contactMessageLabel',contactSend:'contactSend',contactOr:'contactOrText'};Object.entries(ct).forEach(([k,id])=>{const el=document.getElementById(id);if(el&&t[k])el.textContent=t[k]});const ml=document.getElementById('moreLabel');if(ml)ml.textContent=t.more;
 const mainBtns=[...document.querySelectorAll('.chips > button, .chips > .moreWrap > #moreChip')];const labels=[t.all,t.school,t.university,t.language,t.association,t.cervantes,t.teachers];labels.forEach((v,i)=>{if(mainBtns[i])mainBtns[i].innerHTML=v});
 document.getElementById('moreChip').innerHTML='••• <span id="moreLabel">'+t.more+'</span>';
 const addLabel=document.querySelector('.iconAction label');if(addLabel)addLabel.textContent=t.add;const joinStrong=document.querySelector('#joinBtn strong');if(joinStrong)joinStrong.innerHTML=lang==='es'?'Ponte en<br>el mapa':'Put yourself<br>on the map';
 const wc=document.getElementById('worldCard');wc.querySelector('.eyebrow').textContent=t.eyebrow;wc.querySelector('h1').innerHTML=t.headline;wc.querySelector('p').textContent=t.desc;const ms=wc.querySelectorAll('.mini-stats small');ms[0].textContent=t.institutions;ms[1].textContent=t.countries;ms[2].textContent='Cervantes';document.getElementById('explore').textContent=t.exploreMap;
 const tc=document.getElementById('teacherCard');tc.querySelector('.eyebrow').textContent=t.teacherHeart;tc.querySelector('h2').innerHTML=t.put;tc.querySelector('p').textContent=t.teacherDesc;tc.querySelector('.privacy').textContent=t.privacy;tc.querySelector('.teacher-cta').textContent=t.registration;
 const hs=document.querySelectorAll('.headlineStats small');if(hs[0])hs[0].textContent=t.institutions;if(hs[1])hs[1].textContent=t.countries;if(hs[2])hs[2].textContent=t.growth;
 const legends=document.querySelectorAll('.legend span');legends.forEach((el,i)=>{const dot=el.querySelector('i');if(dot&&t.legend[i])el.innerHTML=dot.outerHTML+t.legend[i]});
 const moreLabels=document.querySelectorAll('.moreMenu button span');moreLabels.forEach((el,i)=>{if(t.moreItems[i])el.textContent=t.moreItems[i]});
 const wst=document.querySelector('.worldStatsTitle');if(wst)wst.textContent=lang==='es'?'EXPLORA EL MUNDO DEL ESPAÑOL':'EXPLORE THE SPANISH WORLD';const acc=document.getElementById('accreditedLabel');if(acc)acc.textContent=lang==='es'?'acreditados':'accredited';const afb=document.querySelector('#advancedFilterBtn span');if(afb)afb.textContent=lang==='es'?'Filtros':'Filters';const mab=document.querySelector('#myAtlasBtn small');if(mab){const cnt=document.getElementById('myAtlasCount')?.outerHTML||'';mab.innerHTML=(lang==='es'?'Mi Atlas ':'My Atlas ')+cnt}const cityTitle=document.getElementById('cityBrowserTitle');if(cityTitle)cityTitle.textContent=lang==='es'?'Principales ciudades ELE':'Top ELE cities';const citySearch=document.getElementById('cityBrowserSearch');if(citySearch)citySearch.placeholder=lang==='es'?'Buscar ciudad…':'Search city…';const cbh=document.querySelector('.countryBrowserHead h2');if(cbh)cbh.textContent=lang==='es'?'Explorar por país':'Explore by country';const cbs=document.getElementById('countryBrowserSearch');if(cbs)cbs.placeholder=lang==='es'?'Buscar país…':'Search country…';const setTxt=(sel,en,es)=>{const e=document.querySelector(sel);if(e)e.textContent=lang==='es'?es:en};const setPh=(sel,en,es)=>{const e=document.querySelector(sel);if(e)e.placeholder=lang==='es'?es:en};
setTxt('#adminSubtitle','Private data management','Gestión privada de datos');setTxt('#adminInstitutionsLabel','Institutions','Instituciones');setTxt('#adminCountriesLabel','Countries','Países');setTxt('#adminTeachersLabel','Teachers','Profesores');setTxt('#adminQualityLabel','Data quality','Calidad de datos');setTxt('#manageInstitutions','Institutions','Instituciones');setTxt('#manageInstitutionsDesc','Search, add, edit or remove','Buscar, añadir, editar o eliminar');setTxt('#manageTeachers','Teachers','Profesores');setTxt('#manageTeachersDesc','Registrations and visibility','Solicitudes y visibilidad');setTxt('#manageQuality','Data quality','Calidad de datos');setTxt('#manageQualityDesc','Addresses, coordinates, duplicates','Direcciones, coordenadas y duplicados');setTxt('#manageExport','Export data','Exportar datos');setTxt('#manageExportDesc','Excel / CSV by filter','Excel / CSV por filtros');setTxt('#manageImport','Import data','Importar datos');setTxt('#manageImportDesc','Add or update records in bulk','Añadir o actualizar en bloque');setTxt('#manageAssociations','Associations & More','Asociaciones y más');setTxt('#manageAssociationsDesc','Manage the wider ELE ecosystem','Gestionar el ecosistema ELE');setTxt('#adminSecurityText','Private admin area. Internal emails and contacts must never be exposed in the public map.','Área privada de administración. Los correos y contactos internos nunca deben mostrarse en el mapa público.');setTxt('#scanDuplicates span','Scan possible duplicates','Buscar posibles duplicados');
setPh('#adminSearch','Search institutions…','Buscar instituciones…');setPh('#afCity','Any city','Cualquier ciudad');const afTitle=document.querySelector('.afHead strong');if(afTitle)afTitle.textContent=lang==='es'?'Filtros avanzados':'Advanced filters';setTxt('#afClear','Clear','Limpiar');setTxt('#afApply','Apply filters','Aplicar filtros');const afAcc=document.querySelector('.afCheck span');if(afAcc)afAcc.textContent=lang==='es'?'✓ Solo centros acreditados Cervantes':'✓ Cervantes Accredited only';
setTxt('#myAtlasIntro','Your saved institutions.','Tus instituciones guardadas.');setTxt('#myAtlasClear','Clear','Limpiar');
const tj=tc.querySelectorAll('.teacherJoinForm label');const tjLabels=lang==='es'?['Nombre','Correo electrónico (privado)','Institución','Ciudad','País','Visibilidad pública','Perfil profesional / web']:['Name','Email (private)','Institution','City','Country','Public visibility','Professional profile / website'];tj.forEach((e,i)=>{if(tjLabels[i]){const input=e.querySelector('input,select');e.childNodes[0].nodeValue=tjLabels[i]+' ';}});const tjBtn=tc.querySelector('.teacherJoinForm>button');if(tjBtn)tjBtn.textContent=lang==='es'?'Enviar para revisión →':'Submit for review →';const reg=document.getElementById('teacherRegisterBtn');if(reg)reg.textContent=lang==='es'?'Únete a ATLAS ELE →':'Join ATLAS ELE →';
const stats=document.querySelector('.stats');if(stats)stats.innerHTML='<span class="live"></span><b id="count">5,338</b> '+t.mapped+' <span>·</span> <b id="countries">20+</b> '+t.countries+' <span>·</span> '+t.community;
 // Selector shows the language you can switch TO.
 document.getElementById('langFlag').textContent=lang==='en'?'🇪🇸':'🇬🇧';document.getElementById('langCode').textContent=lang==='en'?'ES':'EN';
 document.getElementById('langSwitch').title=lang==='en'?'Cambiar a español':'Switch to English';
 document.title=lang==='es'?'ATLAS ELE — El mapa mundial de la enseñanza del español':'ATLAS ELE — The global map of Spanish teaching';
}
document.getElementById('langSwitch').onclick=()=>applyLanguage(currentLang==='en'?'es':'en');applyLanguage(currentLang);

const moreMenu=document.getElementById('moreMenu');
document.getElementById('moreChip').addEventListener('click',e=>{e.stopPropagation();moreMenu.classList.toggle('open')});
document.addEventListener('click',e=>{if(!e.target.closest('.moreWrap'))moreMenu.classList.remove('open')});

let globeInstance=null;
const typeColors={school:'#0878d1',university:'#7836ce',language:'#f38b20',association:'#16a66c',teacher:'#eb218e',cervantes:'#d92525'};
function getGlobePoints(source=data){
 const groups=new Map();
 source.forEach(x=>{const key=(+x.lat).toFixed(4)+'|'+(+x.lng).toFixed(4);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(x)});
 return [...groups.values()].map(items=>{if(items.length===1)return {...items[0],count:1,items};const counts={};items.forEach(x=>counts[x.type]=(counts[x.type]||0)+1);const type=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0][0];return {...items[0],type,count:items.length,items,name:items.length+' places'}});
}
function initGlobe(){
 if(globeInstance)return;
 const el=document.getElementById('globeView');
 globeInstance=Globe()(el)
  .globeImageUrl('https://unpkg.com/three-globe/example/img/earth-blue-marble.jpg')
  .bumpImageUrl('https://unpkg.com/three-globe/example/img/earth-topology.png')
  .backgroundImageUrl('https://unpkg.com/three-globe/example/img/night-sky.png')
  .pointsData(getGlobePoints())
  .pointLat(d=>d.lat).pointLng(d=>d.lng).pointColor(d=>typeColors[d.type]||'#0878d1')
  .pointAltitude(d=>.004+Math.min(d.count||1,20)*.00035).pointRadius(d=>.09+Math.min(Math.sqrt(d.count||1)*.035,.16))
  .pointResolution(10)
  .pointLabel(d=>'<div class="globe-tooltip"><b>'+((d.count||1)>1?(d.count+' places'):d.name)+'</b><small>📍 '+d.city+', '+d.country+((d.count||1)>1?'<br>Click to explore this cluster':'<br>🇪🇸 '+d.program)+'</small></div>')
  .onPointClick(d=>{if((d.count||1)>1){setViewMode('2d');map.flyTo([d.lat,d.lng],12,{duration:1.1})}else show(d)});
 globeInstance.controls().autoRotate=true;globeInstance.controls().autoRotateSpeed=.32;
 globeInstance.pointOfView({lat:28,lng:8,altitude:2.15},1200);
 const resize=()=>{globeInstance.width(el.clientWidth).height(el.clientHeight)};resize();window.addEventListener('resize',resize);
}
function setViewMode(mode){
 const is3=mode==='3d';document.body.classList.toggle('globe-mode',is3);document.getElementById('globeView').classList.toggle('active',is3);
 document.getElementById('map2d').classList.toggle('active',!is3);document.getElementById('globe3d').classList.toggle('active',is3);
 if(is3){initGlobe();setTimeout(()=>{const el=document.getElementById('globeView');globeInstance.width(el.clientWidth).height(el.clientHeight)},50)}else{setTimeout(()=>map.invalidateSize(),50)}
}
document.getElementById('globe3d').onclick=()=>setViewMode('3d');
document.getElementById('map2d').onclick=()=>setViewMode('2d');

function initMiniGlobe(){
 const el=document.getElementById('miniGlobe'); if(!el || typeof Globe!=='function') return;
 try{
  const g=Globe()(el)
   .width(58).height(58)
   .globeImageUrl('https://unpkg.com/three-globe/example/img/earth-blue-marble.jpg')
   .bumpImageUrl('https://unpkg.com/three-globe/example/img/earth-topology.png')
   .backgroundColor('rgba(0,0,0,0)')
   .showAtmosphere(true).atmosphereColor('#7ad9ff').atmosphereAltitude(.12);
  g.pointOfView({lat:20,lng:-10,altitude:1.75},0);
  const ctl=g.controls();ctl.autoRotate=true;ctl.autoRotateSpeed=.8;ctl.enableZoom=false;ctl.enablePan=false;ctl.enableRotate=false;
 }catch(e){ el.textContent='🌍'; el.style.fontSize='42px'; el.style.display='grid'; el.style.placeItems='center'; }
}
initMiniGlobe();

async function loadPublicMapData(){
 try{
  const r=await fetch('data/pilot-city-points.json?v=2',{cache:'no-store'});if(!r.ok)throw new Error('data '+r.status);
  const payload=await r.json();const pilot=(payload.institutions||[]).map(x=>({...x,program:x.program||'Spanish / ELE',verified:x.verified??false,web:x.web||''}));
  const spain=(window.ATLAS_SPAIN||[]).map(a=>({id:a[0],name:a[1],type:a[2],city:a[3],country:a[4],lat:a[5],lng:a[6],web:a[7]||'',verified:a[8],address:a[9]||'',precision:a[10]||'city',program:'Spanish / ELE'}));
  const central=(window.ATLAS_CENTRAL||[]).map(a=>({id:a[0],name:a[1],type:a[2],city:a[3],country:a[4],lat:a[5],lng:a[6],web:a[7]||'',verified:a[8],precision:'city',program:'Spanish / ELE'}));
  const globalSeed=(window.ATLAS_GLOBAL||[]).map(a=>({id:a[0],name:a[1],type:a[2],city:a[3],country:a[4],lat:a[5],lng:a[6],web:a[7]||'',verified:a[8],precision:'city',program:'Spanish / ELE'}));const cervantes=(window.ATLAS_CERVANTES||[]).map(a=>({id:a[0],name:a[1],type:'cervantes',city:a[3],country:a[4],lat:a[5],lng:a[6],web:a[7]||'',verified:true,precision:'city',program:'Instituto Cervantes network'}));const accredited=(window.ATLAS_ACCREDITED||[]).map(a=>({id:a[0],name:a[1],type:a[2],city:a[3],country:a[4],lat:a[5],lng:a[6],web:a[7]||'',verified:a[8],address:a[9]||'',precision:'address',program:'Spanish / ELE',accreditation:'Instituto Cervantes Accredited'}));const ukMaster=(window.ATLAS_UK_MASTER||[]).map(a=>({id:a[0],name:a[1],type:a[2],city:a[3],country:a[4],lat:a[5],lng:a[6],web:a[7]||'',verified:a[8],precision:'region',program:'Spanish / MFL'}));const ukMaster2=(window.ATLAS_UK_MASTER_2||[]).map(a=>({id:a[0],name:a[1],type:a[2],city:a[3],country:a[4],lat:a[5],lng:a[6],web:a[7]||'',verified:a[8],precision:'region',program:'Spanish / MFL'}));const ukMaster3=(window.ATLAS_UK_MASTER_3||[]).map(a=>({id:a[0],name:a[1],type:a[2],city:a[3],country:a[4],lat:a[5],lng:a[6],web:a[7]||'',verified:a[8],precision:'region',program:'Spanish / MFL'}));const ukMaster4=(window.ATLAS_UK_MASTER_4||[]).map(a=>({id:a[0],name:a[1],type:a[2],city:a[3],country:a[4],lat:a[5],lng:a[6],web:a[7]||'',verified:a[8],precision:'region',program:'Spanish / MFL'}));const ukMaster5=(window.ATLAS_UK_MASTER_5||[]).map(a=>({id:a[0],name:a[1],type:a[2],city:a[3],country:a[4],lat:a[5],lng:a[6],web:a[7]||'',verified:a[8],precision:'region',program:'Spanish / MFL'}));const ukMaster6=(window.ATLAS_UK_MASTER_6||[]).map(a=>({id:a[0],name:a[1],type:a[2],city:a[3],country:a[4],lat:a[5],lng:a[6],web:a[7]||'',verified:a[8],precision:'region',program:'Spanish / MFL'}));const masterEurope=(window.ATLAS_MASTER_EUROPE||[]).map(a=>({id:a[0],name:a[1],type:a[2],city:a[3],country:a[4],lat:a[5],lng:a[6],web:a[7]||'',verified:a[8],precision:'city',program:'Spanish / ELE'}));let packedMaster=[];try{const parts=window.ATLAS_PACKED_PARTS||[];if(parts.length>=8){const b64=parts.join('');const bin=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));const ds=new DecompressionStream('deflate');const txt=await new Response(new Blob([bin]).stream().pipeThrough(ds)).text();packedMaster=JSON.parse(txt).map(a=>({id:a[0],name:a[1],type:a[2],city:a[3],country:a[4],lat:a[5],lng:a[6],web:a[7]||'',verified:a[8],precision:a[9]||'city',program:'Spanish / MFL'}));console.info('[ATLAS] packed master loaded',packedMaster.length)}}catch(e){console.error('[ATLAS] packed master failed',e)}
  const byId=new Map();
  const precisionRank={unknown:0,country:1,region:2,city:3,address:4,exact:5};
  function mergeRecord(x,source){
    const old=byId.get(x.id);
    if(!old){byId.set(x.id,{...x,_source:source});return}
    const oldRank=precisionRank[old.precision||'unknown']||0,newRank=precisionRank[x.precision||'unknown']||0;
    if(newRank>oldRank){console.info('[ATLAS] upgraded location',x.id,old.precision,'→',x.precision,source);byId.set(x.id,{...old,...x,_source:source});return}
    if(newRank===oldRank){
      const merged={...old};
      for(const [k,v] of Object.entries(x)){if((merged[k]===undefined||merged[k]===null||merged[k]==='')&&v!==undefined&&v!==null&&v!=='')merged[k]=v}
      byId.set(x.id,merged);console.warn('[ATLAS] duplicate ID kept first location',x.id,old._source,'vs',source);return
    }
    console.warn('[ATLAS] protected higher-precision location',x.id,old.precision,'from',x.precision,source);
  }
  pilot.forEach(x=>mergeRecord(x,'pilot'));spain.forEach(x=>mergeRecord(x,'spain'));central.forEach(x=>mergeRecord(x,'central-europe'));globalSeed.forEach(x=>{if(/(?:Instituto|Aula|Extensión|Antena|Cátedra) Cervantes/i.test(x.name))x.type='cervantes';mergeRecord(x,'global-seed')});cervantes.forEach(x=>mergeRecord(x,'cervantes-2025'));accredited.forEach(x=>mergeRecord(x,'cervantes-accredited'));ukMaster.forEach(x=>mergeRecord(x,'uk-master'));ukMaster2.forEach(x=>mergeRecord(x,'uk-master-2'));ukMaster3.forEach(x=>mergeRecord(x,'uk-master-3'));ukMaster4.forEach(x=>mergeRecord(x,'uk-master-4'));ukMaster5.forEach(x=>mergeRecord(x,'uk-master-5'));ukMaster6.forEach(x=>mergeRecord(x,'uk-master-6'));masterEurope.forEach(x=>mergeRecord(x,'master-europe'));packedMaster.forEach(x=>mergeRecord(x,'master-packed'));data=[...byId.values()];const fd=window.ATLAS_FEDELE;if(fd){const normF=v=>(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();for(const [name,city] of fd.members){const n=normF(name),c=normF(city);const hit=data.find(x=>x.country==='Spain'&&normF(x.city)===c&&(normF(x.name)===n||normF(x.name).includes(n)||n.includes(normF(x.name))));if(hit){hit.fedele=true;hit.accreditation=hit.accreditation||'Instituto Cervantes Accredited'}}const a=fd.association;if(!data.some(x=>x.id==='ES-FEDELE-001'))data.push({id:'ES-FEDELE-001',name:a[0],type:a[1],city:a[2],country:a[3],lat:a[4],lng:a[5],web:a[6],address:a[7],verified:true,precision:'address',program:'Federación de Escuelas de Español como Lengua Extranjera',fedele:true});for(const a of (window.ATLAS_FEDELE_ANDALUCIA||[])){const [name,type,city,country,lat,lng,web,phone,address]=a,n=normF(name),c=normF(city);let hit=data.find(x=>x.country===country&&normF(x.city)===c&&(normF(x.name)===n||normF(x.name).includes(n)||n.includes(normF(x.name))));if(hit){hit.fedele=true;hit.accreditation=hit.accreditation||'Instituto Cervantes Accredited';hit.web=hit.web||web;hit.phone=hit.phone||phone;hit.address=hit.address||address;if((precisionRank[hit.precision||'unknown']||0)<4){hit.lat=lat;hit.lng=lng;hit.precision='address'}}else data.push({id:'ES-FEDELE-A-'+String(data.length+1),name,type,city,country,lat,lng,web,phone,address,verified:true,precision:'address',program:'Spanish / ELE',fedele:true,accreditation:'Instituto Cervantes Accredited'})}}
  for(const a of (window.ATLAS_FEDELE_ANDALUCIA_2||[])){const [name,type,city,country,lat,lng,web]=a;const nf=v=>(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim(),n=nf(name),ct=nf(city);let hit=data.find(x=>x.country===country&&nf(x.city)===ct&&(nf(x.name)===n||nf(x.name).includes(n)||n.includes(nf(x.name))));if(hit){hit.fedele=true;hit.accreditation=hit.accreditation||'Instituto Cervantes Accredited';hit.web=hit.web||web}else data.push({id:'ES-FEDELE-B-'+(data.length+1),name,type,city,country,lat,lng,web,verified:true,precision:'city',program:'Spanish / ELE',fedele:true,accreditation:'Instituto Cervantes Accredited'})}
  render();
  const hs=document.querySelectorAll('.headlineStats strong');if(hs[0])hs[0].textContent=data.length.toLocaleString();if(hs[1])hs[1].textContent=new Set(data.map(x=>x.country)).size;
  const ms=document.querySelectorAll('.mini-stats strong');if(ms[0])ms[0].textContent=data.length.toLocaleString();if(ms[1])ms[1].textContent=new Set(data.map(x=>x.country)).size;
  if(globeInstance)globeInstance.pointsData(getGlobePoints());
 }catch(e){console.error('ATLAS ELE data load failed',e)}
}
loadPublicMapData();

const teacherJoinForm=document.getElementById('teacherJoinForm');document.getElementById('teacherRegisterBtn').onclick=()=>teacherJoinForm.classList.toggle('open');function pendingSubmissions(){try{return JSON.parse(localStorage.getItem('atlasPendingTeachers')||'[]')}catch(e){return[]}}function savePendingSubmissions(v){localStorage.setItem('atlasPendingTeachers',JSON.stringify(v));updatePendingCount()}function updatePendingCount(){const n=pendingSubmissions().length,e=document.getElementById('pendingCount');if(e)e.textContent=n;const t=document.getElementById('adminTeachers');if(t)t.textContent=n}teacherJoinForm.onsubmit=e=>{e.preventDefault();const v=pendingSubmissions();v.push({id:'SUB-'+Date.now(),name:document.getElementById('tjName').value.trim(),email:document.getElementById('tjEmail').value.trim(),institution:document.getElementById('tjInstitution').value.trim(),city:document.getElementById('tjCity').value.trim(),country:document.getElementById('tjCountry').value.trim(),visibility:document.getElementById('tjVisibility').value,web:document.getElementById('tjWeb').value.trim(),status:'pending',submitted:new Date().toISOString()});savePendingSubmissions(v);teacherJoinForm.reset();document.getElementById('tjStatus').textContent=currentLang==='es'?'✓ Solicitud enviada para revisión':'✓ Submitted for review'};updatePendingCount();
const adminPanel=document.getElementById('adminPanel');
document.getElementById('adminBtn').onclick=()=>{adminPanel.classList.add('open');teacherCard.classList.remove('open');document.getElementById('adminInstitutions').textContent=data.length.toLocaleString();document.getElementById('adminCountries').textContent=new Set(data.map(x=>x.country)).size};
document.getElementById('adminClose').onclick=()=>adminPanel.classList.remove('open');

function savedIds(){try{return JSON.parse(localStorage.getItem('atlasSaved')||'[]')}catch(e){return[]}}function isSaved(id){return savedIds().includes(id)}function updateMyAtlasCount(){const e=document.getElementById('myAtlasCount');if(e)e.textContent=savedIds().length}function toggleSaved(id){let v=savedIds();v=v.includes(id)?v.filter(x=>x!==id):[...v,id];localStorage.setItem('atlasSaved',JSON.stringify(v));updateMyAtlasCount();renderMyAtlas()}function myAtlasRows(){const set=new Set(savedIds());return data.filter(x=>set.has(x.id))}const cityBrowser=document.getElementById('cityBrowser');function cityCounts(){const m=new Map();data.forEach(x=>{if(!x.city)return;const k=x.city+'|'+x.country;if(!m.has(k))m.set(k,{city:x.city,country:x.country,count:0});m.get(k).count++});return [...m.values()].sort((a,b)=>b.count-a.count||a.city.localeCompare(b.city))}function renderCityBrowser(){const q=normSearch(document.getElementById('cityBrowserSearch')?.value||''),rows=cityCounts().filter(x=>!q||normSearch(x.city).includes(q)||normSearch(x.country).includes(q)),el=document.getElementById('cityBrowserList');if(!el)return;el.innerHTML=rows.slice(0,300).map((x,i)=>'<button data-city-open="'+encodeURIComponent(x.city)+'" data-city-country="'+encodeURIComponent(x.country)+'"><span class="cbRank">'+(i+1)+'</span><b>'+countryFlag(x.country)+'</b><span><strong>'+x.city+'</strong><small>'+x.country+' · '+x.count.toLocaleString()+' '+(currentLang==='es'?'instituciones':'institutions')+'</small></span><em>›</em></button>').join('');el.querySelectorAll('[data-city-open]').forEach(b=>b.onclick=()=>{const city=decodeURIComponent(b.dataset.cityOpen),country=decodeURIComponent(b.dataset.cityCountry),rs=data.filter(x=>x.city===city&&x.country===country);cityBrowser.classList.remove('open');fitRecords(rs,12);showPlaceDirectory(city,rs,'city')})}document.getElementById('browseCitiesBtn').onclick=()=>{document.getElementById('moreMenu').classList.remove('open');document.getElementById('cityBrowserSearch').value='';renderCityBrowser();cityBrowser.classList.add('open')};document.getElementById('cityBrowserClose').onclick=()=>cityBrowser.classList.remove('open');document.getElementById('cityBrowserSearch').oninput=renderCityBrowser;
const countryBrowser=document.getElementById('countryBrowser');function countryFlag(country){const map={'Spain':'🇪🇸','Slovakia':'🇸🇰','United Kingdom':'🇬🇧','United States':'🇺🇸','Germany':'🇩🇪','France':'🇫🇷','Italy':'🇮🇹','Austria':'🇦🇹','Canada':'🇨🇦','Mexico':'🇲🇽','Brazil':'🇧🇷','Argentina':'🇦🇷','Portugal':'🇵🇹','Netherlands':'🇳🇱','Belgium':'🇧🇪','Switzerland':'🇨🇭','Poland':'🇵🇱','Czechia':'🇨🇿','Hungary':'🇭🇺','Romania':'🇷🇴','Japan':'🇯🇵','China':'🇨🇳','India':'🇮🇳','Australia':'🇦🇺','Russia':'🇷🇺','South Korea':'🇰🇷','Ireland':'🇮🇪','Sweden':'🇸🇪','Norway':'🇳🇴','Finland':'🇫🇮','Denmark':'🇩🇰','Greece':'🇬🇷','Croatia':'🇭🇷','Slovenia':'🇸🇮','Serbia':'🇷🇸'};return map[country]||'🌐'}function countryCounts(){const m=new Map();data.forEach(x=>{if(x.country)m.set(x.country,(m.get(x.country)||0)+1)});return [...m].map(([country,count])=>({country,count})).sort((a,b)=>b.count-a.count||a.country.localeCompare(b.country))}function renderCountryBrowser(){const q=normSearch(document.getElementById('countryBrowserSearch')?.value||''),rows=countryCounts().filter(x=>!q||normSearch(x.country).includes(q)),el=document.getElementById('countryBrowserList');if(!el)return;el.innerHTML=rows.map((x,i)=>'<button data-country-open="'+x.country+'"><span class="cbRank">'+(i+1)+'</span><b>'+countryFlag(x.country)+'</b><span><strong>'+x.country+'</strong><small>'+x.count.toLocaleString()+' '+(currentLang==='es'?'instituciones':'institutions')+'</small></span><em>›</em></button>').join('');el.querySelectorAll('[data-country-open]').forEach(b=>b.onclick=()=>{const rows=data.filter(x=>x.country===b.dataset.countryOpen);countryBrowser.classList.remove('open');fitRecords(rows,6);showPlaceDirectory(b.dataset.countryOpen,rows,'country')})}document.getElementById('browseCountriesBtn').onclick=()=>{document.getElementById('moreMenu').classList.remove('open');document.getElementById('countryBrowserSearch').value='';renderCountryBrowser();countryBrowser.classList.add('open')};document.getElementById('countryBrowserClose').onclick=()=>countryBrowser.classList.remove('open');document.getElementById('countryBrowserSearch').oninput=renderCountryBrowser;
const myAtlasPanel=document.getElementById('myAtlasPanel');function renderMyAtlas(){const rows=myAtlasRows(),el=document.getElementById('myAtlasList');if(!el)return;el.innerHTML=rows.length?rows.map(x=>'<div class="myAtlasItem"><button data-ma-open="'+x.id+'"><i class="dirDot type-'+x.type+'"></i><span><strong>'+x.name+'</strong><small>'+x.city+', '+x.country+'</small></span></button><button class="maRemove" data-ma-remove="'+x.id+'">×</button></div>').join(''):'<div class="pendingEmpty">♡ '+(currentLang==='es'?'Todavía no has guardado instituciones':'No saved institutions yet')+'</div>';el.querySelectorAll('[data-ma-open]').forEach(b=>b.onclick=()=>{const x=data.find(r=>r.id===b.dataset.maOpen);if(x){myAtlasPanel.classList.remove('open');map.flyTo([x.lat,x.lng],15,{duration:.8});show(x)}});el.querySelectorAll('[data-ma-remove]').forEach(b=>b.onclick=()=>toggleSaved(b.dataset.maRemove));updateMyAtlasCount()}document.getElementById('myAtlasBtn').onclick=()=>{renderMyAtlas();myAtlasPanel.classList.add('open');adminPanel.classList.remove('open');teacherCard.classList.remove('open')};document.getElementById('myAtlasClose').onclick=()=>myAtlasPanel.classList.remove('open');document.getElementById('myAtlasClear').onclick=()=>{localStorage.removeItem('atlasSaved');renderMyAtlas()};function downloadMyAtlasCsv(){const rows=myAtlasRows();if(!rows.length)return;const fields=exportFields(),out=[fields.join(','),...rows.map(x=>fields.map(f=>'"'+String(x[f]??'').replace(/"/g,'""')+'"').join(','))];const blob=new Blob([out.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='My_ATLAS_ELE.csv';a.click();URL.revokeObjectURL(a.href)}function downloadMyAtlasXlsx(){const rows=myAtlasRows();if(!rows.length)return;const fields=exportFields(),out=rows.map(x=>Object.fromEntries(fields.map(f=>[f,x[f]??''])));const ws=XLSX.utils.json_to_sheet(out),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'My Atlas');XLSX.writeFile(wb,'My_ATLAS_ELE.xlsx')}document.getElementById('myAtlasCsv').onclick=downloadMyAtlasCsv;document.getElementById('myAtlasXlsx').onclick=downloadMyAtlasXlsx;updateMyAtlasCount();
const contactPanel=document.getElementById('contactPanel');
document.getElementById('contactBtn').onclick=()=>{contactPanel.classList.add('open');adminPanel.classList.remove('open');teacherCard.classList.remove('open')};
document.getElementById('contactClose').onclick=()=>contactPanel.classList.remove('open');

document.getElementById('contactForm').addEventListener('submit',e=>{e.preventDefault();const name=document.getElementById('contactName').value.trim(),email=document.getElementById('contactEmail').value.trim(),subject=document.getElementById('contactSubject').value.trim(),message=document.getElementById('contactMessage').value.trim();const body=(currentLang==='es'?'Nombre: ':'Name: ')+name+'\nEmail: '+email+'\n\n'+message;window.location.href='mailto:info@atlasele.org?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body)});

const adminWorkspace=document.getElementById('adminWorkspace'),adminGrid=document.querySelector('.adminGrid');
function qualityIssue(x){if(!Number.isFinite(+x.lat)||!Number.isFinite(+x.lng)||(+x.lat===0&&+x.lng===0))return 'invalid';if((x.precision||'unknown')==='region')return 'region';if((x.precision||'unknown')==='city')return 'city';if(!x.web)return 'web';return null}function updateQualityPriority(){const el=document.getElementById('qualityPriority');if(!el)return;const labels=currentLang==='es'?{invalid:'Coordenadas inválidas',region:'Ubicación regional',city:'Solo ciudad',web:'Sin web'}:{invalid:'Invalid coordinates',region:'Region-level',city:'City-level only',web:'Missing website'};const icons={invalid:'🔴',region:'🟠',city:'🟡',web:'⚪'};el.innerHTML=['invalid','region','city','web'].map(k=>{const n=data.filter(x=>qualityIssue(x)===k).length;return '<button data-quality-issue="'+k+'"><span>'+icons[k]+'</span><b>'+n.toLocaleString()+'</b><small>'+labels[k]+'</small></button>'}).join('');el.querySelectorAll('[data-quality-issue]').forEach(b=>b.onclick=()=>renderQualityIssue(b.dataset.qualityIssue))}function renderQualityIssue(issue){const rows=data.filter(x=>qualityIssue(x)===issue),el=document.getElementById('adminTable');const labels=currentLang==='es'?{invalid:'Coordenadas inválidas',region:'Ubicación regional',city:'Ubicación solo por ciudad',web:'Registros sin web'}:{invalid:'Invalid coordinates',region:'Region-level locations',city:'City-level locations',web:'Records missing website'};document.getElementById('adminWorkTitle').textContent=labels[issue];document.getElementById('adminWorkSub').textContent=rows.length.toLocaleString()+' '+(currentLang==='es'?'registros para revisar':'records to review');el.innerHTML=rows.slice(0,500).map(x=>'<div class="adminRow quality-'+issue+'"><div><strong>'+x.name+'</strong><small>'+x.city+', '+x.country+' · '+(x.precision||'unknown')+'</small></div><span class="type">'+x.type+'</span><button data-edit="'+x.id+'">✎</button></div>').join('');el.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editAdminRecord(b.dataset.edit))}
function duplicateKeyName(v){return normSearch(v||'').replace(/\b(university|universidad|universite|universitat|universita|school|colegio|college|academy|academia|instituto|institute|language|languages|spanish|espanol|español|the|of|de|del|la|el)\b/g,' ').replace(/\s+/g,' ').trim()}function possibleDuplicates(){const groups=new Map();data.forEach(x=>{const n=duplicateKeyName(x.name);if(n.length<4)return;const k=n+'|'+normSearch(x.city||'')+'|'+normSearch(x.country||'');if(!groups.has(k))groups.set(k,[]);groups.get(k).push(x)});return [...groups.values()].filter(g=>g.length>1)}function updateDuplicateCount(){const e=document.getElementById('duplicateCount');if(e)e.textContent=possibleDuplicates().reduce((n,g)=>n+g.length,0)}function renderDuplicates(){const groups=possibleDuplicates(),el=document.getElementById('adminTable');document.getElementById('adminWorkTitle').textContent=currentLang==='es'?'Posibles duplicados':'Possible duplicates';document.getElementById('adminWorkSub').textContent=currentLang==='es'?'Revisión manual: nunca se elimina automáticamente':'Manual review — nothing is deleted automatically';el.innerHTML=groups.length?groups.slice(0,150).map(g=>'<div class="duplicateGroup"><div class="dupHead"><b>⚠ '+g.length+' '+(currentLang==='es'?'registros similares':'similar records')+'</b><small>'+g[0].city+', '+g[0].country+'</small></div>'+g.map(x=>'<div class="dupRecord"><span><strong>'+x.name+'</strong><small>'+x.id+' · '+(x._source||'source unknown')+' · '+(x.precision||'unknown')+'</small></span><button data-dup-open="'+x.id+'">✎</button></div>').join('')+'</div>').join(''):'<div class="pendingEmpty">✓ '+(currentLang==='es'?'No se han detectado duplicados claros':'No clear duplicates detected')+'</div>';el.querySelectorAll('[data-dup-open]').forEach(b=>b.onclick=()=>editAdminRecord(b.dataset.dupOpen))}document.getElementById('scanDuplicates').onclick=renderDuplicates;
function updateAdminQuality(){const el=document.getElementById('adminQualityStrip');if(!el)return;const ps=['exact','address','city','region','unknown'];const labels=currentLang==='es'?{exact:'Exacta',address:'Dirección',city:'Por ciudad',region:'Regional',unknown:'Por revisar'}:{exact:'Exact',address:'Address',city:'City-level',region:'Region-level',unknown:'Unknown'};el.innerHTML=ps.map(p=>{const n=data.filter(x=>(x.precision||'unknown')===p).length;return '<button data-qprecision="'+p+'"><b>'+n.toLocaleString()+'</b><small>'+labels[p]+'</small></button>'}).join('');el.querySelectorAll('[data-qprecision]').forEach(b=>b.onclick=()=>{document.getElementById('adminPrecision').value=b.dataset.qprecision;renderAdminRows('quality')})}
function populateAdminCountries(){const e=document.getElementById('adminCountry');if(!e)return;const v=e.value;e.innerHTML='<option value="all">All countries</option>'+[...new Set(data.map(x=>x.country))].sort().map(x=>'<option>'+x+'</option>').join('');if([...e.options].some(o=>o.value===v))e.value=v}
function openAdminWorkspace(mode){
 adminPanel.classList.add('workspace');adminWorkspace.classList.add('open');
 if(mode==='institutions'||mode==='quality'){populateAdminCountries();updateAdminQuality();updateDuplicateCount();updateQualityPriority();document.getElementById('duplicateTools').style.display=mode==='quality'?'block':'none';document.getElementById('qualityPriority').style.display=mode==='quality'?'grid':'none';document.getElementById('adminWorkTitle').textContent=mode==='quality'?'Data quality':'Institutions';document.getElementById('adminWorkSub').textContent=mode==='quality'?'Review location precision and records':'Search and edit public map records';renderAdminRows(mode)}
 if(mode==='teachers'){document.getElementById('duplicateTools').style.display='none';document.getElementById('qualityPriority').style.display='none';document.getElementById('adminWorkTitle').textContent='Pending submissions';document.getElementById('adminWorkSub').textContent='Approve, edit or reject community registrations';adminWorkspace.querySelector('.adminControls').style.display='none';document.getElementById('adminQualityStrip').innerHTML='';renderPendingSubmissions()}
 if(mode==='export'){document.getElementById('duplicateTools').style.display='none';document.getElementById('qualityPriority').style.display='none';document.getElementById('adminWorkTitle').textContent='Export data';document.getElementById('adminWorkSub').textContent='Filter and select exactly what you want';adminWorkspace.querySelector('.adminControls').style.display='none';renderExportBuilder()}
}
function closeAdminWorkspace(){adminPanel.classList.remove('workspace');adminWorkspace.classList.remove('open');adminWorkspace.querySelector('.adminControls').style.display='grid'}
document.getElementById('adminBack').onclick=closeAdminWorkspace;
document.querySelectorAll('.adminGrid button').forEach(b=>b.onclick=()=>{const m=b.dataset.admin;if(['institutions','quality','export','teachers'].includes(m))openAdminWorkspace(m)});
function renderPendingSubmissions(){const rows=pendingSubmissions(),el=document.getElementById('adminTable');el.innerHTML=rows.length?rows.map(x=>'<div class="pendingSubmission"><div><strong>'+x.name+'</strong><small>'+x.city+', '+x.country+(x.institution?' · '+x.institution:'')+'</small><em>🔒 '+x.email+' · '+x.visibility+'</em></div><div><button data-pa="'+x.id+'">Approve</button><button data-pr="'+x.id+'">Reject</button></div></div>').join(''):'<div class="pendingEmpty">✓ No pending submissions</div>';el.querySelectorAll('[data-pa]').forEach(b=>b.onclick=()=>approveSubmission(b.dataset.pa));el.querySelectorAll('[data-pr]').forEach(b=>b.onclick=()=>rejectSubmission(b.dataset.pr))}function approveSubmission(id){let v=pendingSubmissions(),x=v.find(r=>r.id===id);if(!x)return;if(x.visibility!=='private'){data.push({id:'TEACHER-'+Date.now(),name:x.name,type:'teacher',city:x.city,country:x.country,lat:0,lng:0,web:x.web||'',verified:false,precision:x.visibility==='country'?'country':'city',program:'Spanish / ELE',institution:x.institution||'',visibility:x.visibility})}v=v.filter(r=>r.id!==id);savePendingSubmissions(v);render();renderPendingSubmissions()}function rejectSubmission(id){savePendingSubmissions(pendingSubmissions().filter(r=>r.id!==id));renderPendingSubmissions()}
function renderAdminRows(mode='institutions'){
 const q=document.getElementById('adminSearch').value.toLowerCase(),typ=document.getElementById('adminType').value,country=document.getElementById('adminCountry')?.value||'all',precision=document.getElementById('adminPrecision')?.value||'all';
 let rows=data.filter(x=>(typ==='all'||x.type===typ)&&(country==='all'||x.country===country)&&(precision==='all'||(x.precision||'unknown')===precision)&&(!q||[x.name,x.city,x.country,x.id].some(v=>(v||'').toLowerCase().includes(q))));
 if(mode==='quality')rows=rows.sort((a,b)=>(a.precision==='exact'?1:0)-(b.precision==='exact'?1:0));
 document.getElementById('adminTable').innerHTML=rows.slice(0,300).map(x=>'<div class="adminRow"><div><strong>'+x.name+'</strong><small>'+x.city+', '+x.country+' · '+(x.precision||'unknown')+'</small></div><span class="type">'+x.type+'</span><button data-edit="'+x.id+'">✎</button></div>').join('');
 document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editAdminRecord(b.dataset.edit));
}
document.getElementById('adminSearch').oninput=()=>renderAdminRows();['adminType','adminCountry','adminPrecision'].forEach(id=>document.getElementById(id).onchange=()=>renderAdminRows());
function editAdminRecord(id){const x=data.find(r=>r.id===id);if(!x)return;document.getElementById('adminTable').innerHTML='<div class="adminEdit"><label>Name<input id="aeName" value="'+escAttr(x.name)+'"></label><label>City<input id="aeCity" value="'+escAttr(x.city)+'"></label><label>Country<input id="aeCountry" value="'+escAttr(x.country)+'"></label><label>Address<input id="aeAddress" value="'+escAttr(x.address||'')+'"></label><label>Latitude<input id="aeLat" type="number" step="any" value="'+x.lat+'"></label><label>Longitude<input id="aeLng" type="number" step="any" value="'+x.lng+'"></label><label>Website<input id="aeWeb" value="'+escAttr(x.web||'')+'"></label><div class="adminEditActions"><button class="adminSave" id="aeSave">Save locally</button><button class="adminDelete" id="aeDelete">Remove locally</button></div></div>';document.getElementById('aeSave').onclick=()=>{Object.assign(x,{name:document.getElementById('aeName').value,city:document.getElementById('aeCity').value,country:document.getElementById('aeCountry').value,address:document.getElementById('aeAddress').value,lat:+document.getElementById('aeLat').value,lng:+document.getElementById('aeLng').value,web:document.getElementById('aeWeb').value,precision:'exact'});render();renderAdminRows()};document.getElementById('aeDelete').onclick=()=>{data=data.filter(r=>r.id!==id);render();renderAdminRows()}}
function escAttr(v){return String(v??'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;')}
function exportFields(){return ['id','name','type','city','country','address','lat','lng','precision','web','verified','program']}
let exportSelected=new Set();
function renderExportBuilder(){
 const countries=[...new Set(data.map(x=>x.country))].sort();
 adminWorkspace.querySelector('.adminTable').innerHTML='<div class="exportBuilder"><div class="exportFilters"><select id="exType"><option value="all">All types</option><option value="school">Schools</option><option value="university">Universities</option><option value="language">Language schools</option><option value="official">Official institutions</option><option value="association">Associations</option><option value="teacher">Teachers</option></select><select id="exCountry"><option value="all">All countries</option>'+countries.map(x=>'<option>'+x+'</option>').join('')+'</select><input id="exCity" placeholder="City"><input id="exSearch" placeholder="Search name…"></div><div class="exportActions"><button id="exAll">Select visible</button><button id="exNone">Clear all</button><strong id="exCount">0 selected</strong></div><div class="exportList" id="exportList"></div><div class="exportDownload"><button class="exportXlsx" id="downloadXlsx">⇩ Excel (.xlsx)</button><button class="exportCsv" id="downloadCsv">⇩ CSV</button></div></div>';
 ['exType','exCountry'].forEach(id=>document.getElementById(id).onchange=renderExportList);['exCity','exSearch'].forEach(id=>document.getElementById(id).oninput=renderExportList);
 document.getElementById('exAll').onclick=()=>{getExportVisible().forEach(x=>exportSelected.add(x.id));renderExportList()};document.getElementById('exNone').onclick=()=>{exportSelected.clear();renderExportList()};
 document.getElementById('downloadCsv').onclick=downloadSelectedCsv;document.getElementById('downloadXlsx').onclick=downloadSelectedXlsx;renderExportList();
}
function getExportVisible(){const typ=document.getElementById('exType')?.value||'all',country=document.getElementById('exCountry')?.value||'all',city=(document.getElementById('exCity')?.value||'').toLowerCase(),q=(document.getElementById('exSearch')?.value||'').toLowerCase();return data.filter(x=>(typ==='all'||x.type===typ)&&(country==='all'||x.country===country)&&(!city||(x.city||'').toLowerCase().includes(city))&&(!q||(x.name||'').toLowerCase().includes(q)))}
function renderExportList(){const rows=getExportVisible(),el=document.getElementById('exportList');if(!el)return;el.innerHTML=rows.map(x=>'<label class="exportItem"><input type="checkbox" data-ex="'+x.id+'" '+(exportSelected.has(x.id)?'checked':'')+'><span><strong>'+x.name+'</strong><small>'+x.city+', '+x.country+'</small></span><em>'+x.type+'</em></label>').join('');el.querySelectorAll('[data-ex]').forEach(cb=>cb.onchange=()=>{cb.checked?exportSelected.add(cb.dataset.ex):exportSelected.delete(cb.dataset.ex);updateExportCount()});updateExportCount()}
function updateExportCount(){const e=document.getElementById('exCount');if(e)e.textContent=exportSelected.size+' selected'}
function selectedExportData(){return data.filter(x=>exportSelected.has(x.id))}
function downloadSelectedCsv(){const selected=selectedExportData();if(!selected.length)return;const fields=exportFields(),rows=[fields.join(','),...selected.map(x=>fields.map(f=>'"'+String(x[f]??'').replace(/"/g,'""')+'"').join(','))];const blob=new Blob([rows.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ATLAS_ELE_Selected_Data.csv';a.click();URL.revokeObjectURL(a.href)}
function downloadSelectedXlsx(){const selected=selectedExportData();if(!selected.length)return;const fields=exportFields(),rows=selected.map(x=>Object.fromEntries(fields.map(f=>[f,x[f]??''])));const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'ATLAS ELE');XLSX.writeFile(wb,'ATLAS_ELE_Selected_Data.xlsx')}
